version: '3.7'

services:
  minio1:
    image: quay.io/minio/minio:${MINIO_TAG}
    command: server --console-address ":9001" http://minio1/data{1...4}

    expose:
    - '9000'
    - '9001'

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_IDENTITY_LDAP_SERVER_ADDR: ${MINIO_IDENTITY_LDAP_SERVER_ADDR}
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: ${MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN}
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: ${MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN}
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: ${MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER}
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: ${MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD}
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER: ${MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER}
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN: ${MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN}

    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s

    hostname: minio1

    volumes:
    - data-1:/data1:rw
    - data-2:/data2:rw
    - data-3:/data3:rw
    - data-4:/data4:rw

    networks:
      - traefik
      - monitoring-ext

    labels:
    - "traefik.http.routers.${TRAEFIK_MINIO_ROUTER:-minio-dev}.rule=Host(`${TRAEFIK_MINIO_HOST:-minio-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_MINIO_ROUTER:-minio-dev}.service=${TRAEFIK_MINIO_ROUTER:-minio-dev}"
    - "traefik.http.routers.${TRAEFIK_MINIO_ROUTER:-minio-dev}.tls=true"
    - "traefik.http.services.${TRAEFIK_MINIO_ROUTER:-minio-dev}.loadbalancer.server.port=9000"

    - "traefik.http.routers.${TRAEFIK_MINIO_ROUTER:-minio-dev}-admin.rule=Host(`${TRAEFIK_MINO_ADMIN_HOST:-minio-dev-admin.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_MINIO_ROUTER:-minio-dev}-admin.service=${TRAEFIK_MINIO_ROUTER:-minio-dev}-admin"
    - "traefik.http.routers.${TRAEFIK_MINIO_ROUTER:-minio-dev}-admin.tls=true"
    - "traefik.http.services.${TRAEFIK_MINIO_ROUTER:-minio-dev}-admin.loadbalancer.server.port=9001"

    - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
  monitoring-ext:
    external: true

volumes:
  data-1: {}
  data-2: {}
  data-3: {}
  data-4: {}
